awk '/static Future<void> uninstallApp/ {
    print "  static Future<List<Map<String, dynamic>>> getAvailableIconPacks() async {"
    print "    try {"
    print "      final List<dynamic>? packs = await _systemChannel.invokeMethod('\''getAvailableIconPacks'\'');"
    print "      if (packs != null) {"
    print "        return packs.map((p) => Map<String, dynamic>.from(p as Map)).toList();"
    print "      }"
    print "    } catch (e) {"
    print "      print('\''Error fetching icon packs: $e'\'');"
    print "    }"
    print "    return [];"
    print "  }"
    print ""
    print "  static Future<Uint8List?> getThemedIcon(String appPackage, String iconPackPackage) async {"
    print "    try {"
    print "      return await _systemChannel.invokeMethod('\''getThemedIcon'\'', {"
    print "        '\''appPackage'\'': appPackage,"
    print "        '\''iconPackPackage'\'': iconPackPackage,"
    print "      });"
    print "    } catch (e) {"
    print "      print('\''Error fetching themed icon: $e'\'');"
    print "      return null;"
    print "    }"
    print "  }"
    print ""
}
{print}' lib/services/launcher_service.dart > temp.dart && mv temp.dart lib/services/launcher_service.dart
